# strings
STRINGS = {
    "ru": {
        "connect": "Подключить",
        "disconnect": "Отключить",
        "connected": "Подключен",
        "disconnected": "Отключен",
        "connecting": "Подключение...",
        "disconnecting": "Отключение...",
        "toast_connected": "WARP подключен",
        "toast_disconnected": "WARP отключен",
        "toast_error": "Произошла ошибка",
        "toast_saved": "Настройки сохранены",
        "speed": "Скорость",
        "download": "Загрузка",
        "upload": "Отдача",
        "endpoint": "Эндпоинт",
        "language": "Язык",
        "dns": "DNS-сервер",
        "auto_dns": "Авто-выбор DNS",
        "settings": "Настройки",
        "help": "Помощь",
        "stalzone": "STALZONE",
        "apps": "Маршруты",
        "system": "Система",
        "monitor": "Мониторинг",
        "quick": "Основное",
        "control": "Контроль",
        "log": "Журнал",
        "warp_region": "Регион WARP",
        "dns_description": "DNS-сервер преобразует доменные имена в IP-адреса. Быстрый DNS ускоряет загрузку сайтов.",
        "quick_intro": "Одна кнопка - и WARP подключен. Статус, IP и живой график скорости показаны ниже.",
        "quick_hint": "Режим и параметры настраиваются во вкладке \"Контроль\".",
        "mode_label": "Режим",
        "mode_warp": "warp (полный VPN, включая голос)",
        "mode_proxy": "proxy (выборочно, SOCKS5, только TCP)",
        "port_label": "Порт SOCKS5-прокси",
        "endpoint_hint": "Свой эндпоинт WARP (продвинутый, необязательно)",
        "endpoint_placeholder": "или введите свой IP:порт",
        "endpoint_note": "Работает только в режиме warp. Официальный клиент принимает IP:порт.",
        "connect_warp": "Подключить WARP",
        "disconnect_warp": "Отключить",
        "diagnostics": "Диагностика",
        "check_ip": "Проверить IP и страну",
        "log_title": "Журнал",
        "apps_title": "Выборочное проксирование",
        "apps_info": "Отметьте приложения, которые должны идти через прокси. Работает только в режиме proxy (SOCKS5).",
        "search_placeholder": "Поиск по названию...",
        "all_categories": "Все категории",
        "cat_games": "Игры",
        "cat_browsers": "Браузеры",
        "cat_messengers": "Мессенджеры",
        "cat_office": "Офис и документы",
        "cat_dev": "Разработка",
        "cat_media": "Мультимедиа",
        "cat_other": "Другое",
        "refresh_list": "Обновить список",
        "launch_checked": "Запустить отмеченные через прокси",
        "hide_selected": "Скрыть из списка",
        "add_manual": "Добавить приложение вручную",
        "exe_placeholder": "Путь к .exe...",
        "browse": "Обзор",
        "add": "Добавить",
        "sys_title": "Системный прокси (только режим proxy)",
        "sys_check": "Включить системный прокси (весь трафик через SOCKS5)",
        "sys_info": "Направляет трафик системы через SOCKS5-прокси WARP. Часть приложений (например, Firefox) не читает системный прокси Windows - для них настройте прокси внутри самого приложения (socks5, хост 127.0.0.1, порт как указано выше).",
        "utilities": "Утилиты",
        "flush_dns": "Сбросить DNS-кэш",
        "clear_proxy": "Очистить настройки прокси в реестре",
        "stalzone_title": "Принудительный регион для STALZONE",
        "stalzone_info": "Файл sc_forced_realm помещается в корневую папку игры, чтобы задать регион.\nПрограмма автоматически найдет установленную игру и предложит выбрать регион.\nЕсли путь не найден - укажите его вручную.",
        "game_path": "Путь к игре:",
        "stalzone_placeholder": "Например: D:\\Steam\\steamapps\\common\\STALZONE",
        "auto_find": "Найти игру автоматически",
        "select_region": "Выберите регион:",
        "check_ping": "Проверить пинг до регионов",
        "apply_region": "Применить файл региона",
        "stalzone_status": "Статус: не применено",
        "settings_connection": "Соединение",
        "auto_reconnect": "Автопереподключение при обрыве связи",
        "dns_label": "DNS-сервер:",
        "auto_dns_btn": "Авто-выбор",
        "autostart": "Автозапуск",
        "autostart_check": "Запускать XaraProxy вместе с Windows",
        "autostart_action": "При запуске программы:",
        "autostart_nothing": "Ничего не делать - просто открыть окно",
        "autostart_connect": "Сразу подключить WARP",
        "autostart_connect_apps": "Подключить WARP и запустить отмеченные приложения",
        "interface": "Интерфейс",
        "ui_level": "Уровень интерфейса:",
        "lang_label": "Язык:",
        "ui_hint_simple": "\"simple\" - показывает \"Основное\", \"Контроль\", \"Настройки\" и \"Помощь\".",
        "ui_hint_advanced": "\"advanced\" - открывает \"Маршруты\", \"Систему\", \"Мониторинг\" и ручной эндпоинт WARP.\nВкладка STALZONE доступна всегда.",
        "reset": "Сброс",
        "reset_btn": "Сбросить всю конфигурацию",
        "reset_info": "Удалит сохраненные настройки и перезапустит программу.",
        "save_settings": "Сохранить настройки",
        "help_install_title": "Установка WARP",
        "help_status_installed": "Статус: WARP установлен и готов к работе.",
        "help_status_not_installed": "Статус: WARP не найден. Нажмите кнопку ниже для автоматической установки.",
        "help_install_btn": "Скачать и установить WARP",
        "help_install_btn_done": "Установка не требуется",
        "help_instructions": "Инструкция",
        "help_text_proxy": "Режим proxy (выборочно): WARP поднимает локальный SOCKS5-прокси на 127.0.0.1. Через него идут только отмеченные приложения (TCP). Голосовая связь (UDP) через SOCKS5 не работает - используйте warp, если нужен голос.",
        "help_text_warp": "Режим warp (полный VPN): весь трафик компьютера идет через туннель, включая голос, но у всех приложений одновременно меняется видимый регион.",
        "help_text_choose": "Не знаете, что выбрать: начните с \"Основное\" - режим warp, без ручного эндпоинта.",
        "help_text_diagnostics": "Диагностика: кнопка \"Проверить IP и страну\" на вкладке \"Контроль\" покажет, что видят внешние сайты, с учетом реального SOCKS5-туннелирования DNS.",
        "help_text_autostart": "Автозапуск: во вкладке \"Настройки\" можно запускать программу вместе с Windows и сразу подключать WARP (или еще и отмеченные приложения).",
        "help_text_stalzone": "STALZONE: вкладка позволяет принудительно задать регион для игры, создавая файл sc_forced_realm в корневой папке.",
        "help_text_browsers": "Браузеры: Chrome и Edge запускаются с флагом --proxy-server=socks5://127.0.0.1:порт и реально идут через прокси. Firefox не принимает прокси через командную строку - настройте SOCKS5 вручную в about:preferences или используйте расширение FoxyProxy.",
        "tray_connect": "Подключить WARP",
        "tray_disconnect": "Отключить WARP",
        "tray_show": "Показать окно",
        "tray_quit": "Выйти",
        "minimized_to_tray": "Свернуто в трей. WARP продолжает работать.",
        "admin_required": "Нужны права администратора",
        "admin_restart": "Установка WARP требует прав администратора. Перезапустить от имени администратора?",
        "sys_proxy_admin": "Для системного прокси нужны права администратора.",
        "autostart_fail": "Не получилось прописать автозапуск в реестре.",
        "warp_not_installed": "WARP не установлен. Откройте вкладку \"Помощь\".",
        "dns_checking": "Проверка DNS серверов...",
        "dns_fastest": "Самый быстрый DNS: ",
        "app_added": "Добавлено: ",
        "app_exists": "Это приложение уже в списке",
        "select_app": "Выберите приложение для удаления.",
        "hide_confirm": "Скрыть",
        "hide_message": "Скрыть \"%s\" из списка?",
        "no_apps_checked": "Отметьте хотя бы одно приложение",
        "proxy_mode_only": "Эта функция работает только в режиме proxy.",
        "warp_not_connected": "WARP не подключен",
        "start_now": "Запустить сейчас?",
        "connect_first": "Сначала подключите WARP.",
        "checking": "Проверяю...",
        "ip_country": "IP: %s . Страна: %s . WARP: %s",
        "could_not_check": "Не удалось проверить: ",
        "pysocks_missing": "Не установлен пакет PySocks - без него Python не умеет работать с SOCKS5-прокси. Установите: pip install \"requests[socks]\"",
        "mode_changed": "Смена режима - переподключаюсь...",
        "system_proxy_only": "Системный прокси работает только в режиме proxy.",
        "sys_proxy_enabled": "Системный SOCKS5-прокси включен (127.0.0.1:%d)",
        "sys_proxy_failed": "Не удалось включить системный прокси: ",
        "sys_proxy_disabled": "Системный прокси отключен и очищен",
        "dns_flushed": "DNS-кэш сброшен",
        "dns_flush_fail": "Не удалось сбросить DNS: ",
        "proxy_cleared": "Настройки прокси очищены",
        "proxy_clear_fail": "Не удалось очистить настройки: ",
        "settings_saved": "Настройки сохранены",
        "reset_confirm": "Удалить все настройки?",
        "reset_done": "Конфигурация сброшена",
        "reset_fail": "Не удалось сбросить конфиг: ",
        "download_installer": "Загрузка...",
        "download_progress": "Загрузка: %d%% (%.1f / %.1f МБ)",
        "installer_sig_fail": "Подпись установщика недействительна! Установка отменена.",
        "installer_success": "WARP успешно установлен.",
        "installer_error": "Не удалось установить WARP: ",
        "warp_register": "Начинаю регистрацию WARP...",
        "warp_connected": "WARP подключен, IP: %s, регион: %s",
        "warp_disconnected": "WARP отключен",
        "warp_connecting": "Подключение...",
        "warp_failed": "Не удалось подключиться",
        "scanning": "Сканирование",
        "apps_found": "Найдено приложений: ",
        "launched_via_proxy": "Запущено через прокси: ",
        "launch_error": "Ошибка запуска",
        "launched_count": "Запущено приложений: ",
        "launch_firefox_warning": "Firefox не поддерживает прокси из командной строки - настройте SOCKS5 вручную.",
        "stalzone_file_created": "Файл sc_forced_realm создан в %s с регионом %s",
        "stalzone_file_fail": "Не удалось создать файл: ",
        "stalzone_game_found": "Найдена папка игры: ",
        "stalzone_game_not_found": "Не удалось найти папку игры. Укажите путь вручную.",
        "stalzone_path_set": "Путь не указан или не существует.",
        "stalzone_file_exists": "Файл найден, содержимое: ",
        "stalzone_file_empty": "(пусто)",
        "stalzone_file_read_error": "Файл найден, но не удалось прочитать",
        "stalzone_file_missing": "Файл отсутствует. Будет создан при применении.",
        "stalzone_apply_success": "Регион %s применен",
        "stalzone_ping_start": "Проверка пинга до регионов...",
        "stalzone_ping_result": "%s: %d мс",
        "stalzone_ping_unavailable": "%s: недоступен",
        "stalzone_fastest": "Самый быстрый регион: %s (%d мс)",
        "stalzone_ping_fail": "Не удалось определить пинг ни до одного региона.",
        "endpoint_set": "Эндпоинт установлен: ",
        "endpoint_fail": "Не удалось применить пользовательский эндпоинт, использую авто",
        "region_set": "Регион установлен: ",
        "region_fail": "Не удалось установить регион, использую авто",
        "warp_inactive": "WARP неактивен в ответе сервера, возможно трафик не идет через туннель",
        "connection_lost": "Соединение потеряно (попытка %d)",
        "reconnecting": "Переподключение через %d сек...",
        "reconnected": "Переподключено. IP: %s, страна: %s",
        "reconnect_failed": "Переподключение не удалось",
        "reconnect_stop": "Слишком много неудачных попыток - автопереподключение остановлено",
        "registering": "Регистрация устройства...",
        "register_fail": "Не удалось зарегистрировать устройство",
        "mode_set": "Режим установлен",
        "no_endpoint": "Не удалось применить пользовательский эндпоинт, использую авто",
        "monitor_title": "Активные соединения через прокси",
        "monitor_info": "Показывает процессы, у которых есть открытые соединения на локальный порт SOCKS5-прокси.",
        "monitor_col_pid": "PID",
        "monitor_col_name": "Процесс",
        "monitor_col_addr": "Удаленный адрес",
        "monitor_empty": "Нет активных соединений через прокси.",
        "monitor_scan_fail": "Не удалось просканировать соединения: ",
        "security": "Безопасность",
        "security_title": "Центр безопасности",
        "security_intro": "Общий обзор того, что защищает ваше соединение прямо сейчас.",
        "sec_warp_status": "Туннель WARP",
        "sec_kill_switch": "Kill Switch",
        "sec_system_proxy": "Системный прокси",
        "sec_cli_signature": "Подпись warp-cli.exe",
        "sec_state_on": "Активно",
        "sec_state_off": "Выключено",
        "sec_state_unknown": "Неизвестно",
        "sec_signature_ok": "Подпись действительна",
        "sec_signature_bad": "Подпись НЕ подтверждена!",
        "sec_signature_missing": "WARP не найден",
        "leak_test": "Проверить утечку IP/DNS",
        "leak_test_running": "Проверка утечек...",
        "leak_test_ok": "Утечек не обнаружено. Виден только IP Cloudflare.",
        "leak_test_warn": "Внимание: похоже, трафик НЕ проходит через WARP-туннель.",
        "leak_test_fail": "Не удалось выполнить проверку: ",
        "kill_switch_title": "Kill Switch",
        "kill_switch_label": "Блокировать весь интернет при обрыве WARP (Kill Switch)",
        "kill_switch_info": "Добавляет временное правило брандмауэра Windows, блокирующее весь исходящий трафик,\nесли WARP неожиданно отключился. Правило снимается при ручном отключении WARP\nили при выключении Kill Switch. Требует прав администратора.",
        "kill_switch_admin_q": "Kill Switch требует прав администратора для управления брандмауэром. Перезапустить от имени администратора?",
        "kill_switch_blocked_toast": "Kill Switch: интернет заблокирован до восстановления WARP",
        "unsaved_title": "Несохраненные изменения",
        "unsaved_body": "У вас есть несохранённые изменения в настройках. Сохранить их перед выходом?",
        "autostart_default_note": "По умолчанию программа НЕ подключает WARP автоматически - только когда вы сами нажмёте \"Подключить\".",
        "wizard_welcome_title": "Добро пожаловать в XaraProxy",
        "wizard_welcome_body": "XaraProxy - удобная надстройка для управления Cloudflare WARP.\n\nС ней вы можете:\n- Защитить соединение через WARP\n- Направлять отдельные приложения через локальный SOCKS5-прокси\n- Принудительно задавать регион для STALZONE\n- Использовать Kill Switch, чтобы не было утечек при обрыве WARP\n\nСейчас пройдём быструю настройку. XaraProxy НЕ подключается автоматически -\nвы сами решаете, когда подключаться, каждый раз.",
        "wizard_lang_title": "Выбор языка",
        "wizard_lang_body": "Выберите язык интерфейса. Его всегда можно поменять позже во вкладке \"Настройки\".",
        "wizard_lang_label": "Язык интерфейса:",
        "wizard_install_title": "Установка WARP",
        "wizard_install_body": "WARP не найден на вашем компьютере.\nНажмите кнопку ниже, чтобы скачать установщик в папку программы.\nПосле загрузки программа проверит его цифровую подпись.\nЕсли подпись верна - откроется установщик.\n\nВАЖНО: после установки закройте окно WARP, которое откроется автоматически.\nЭто нужно, чтобы данная программа могла корректно им управлять.",
        "wizard_download_btn": "Скачать и запустить установщик WARP",
        "wizard_downloading": "Загрузка...",
        "wizard_final_title": "Регистрация и выбор режима",
        "wizard_final_body": "Подождите, пока мы проверим установку WARP и зарегистрируем устройство.\nЕсли WARP уже установлен или вы только что его установили - нажмите \"Готово\".",
        "wizard_mode_label": "Выберите предпочитаемый режим:",
        "wizard_connect_now": "Подключиться к WARP сразу после завершения настройки",
        "wizard_connect_hint": "Если не отмечено, XaraProxy откроется готовым, но отключенным - вы сами\nнажмёте \"Подключить\", когда захотите. Это рекомендуемый, более безопасный вариант.",
        "watchdog_service_down": "Служба Cloudflare WARP не отвечает - пробую восстановить...",
        "watchdog_service_recovered": "Служба Cloudflare WARP снова работает",
        "sound_enabled_label": "Звуковые уведомления",
        "sound_enabled_info": "Короткие мягкие звуки при подключении, отключении и предупреждениях. Полностью синтезируются программой - никаких сторонних файлов.",
        "diag_export_title": "Диагностика для поддержки",
        "diag_export_info": "Собирает версию, статус WARP, состояние Kill Switch/прокси и последние строки журнала в один файл - без личных данных вроде путей к вашим программам. Приложите этот файл к обращению в поддержку.",
        "diag_export_btn": "Экспортировать диагностику",
        "diag_export_saved": "Файл диагностики сохранён: ",
        "diag_export_fail": "Не удалось сохранить файл: ",
        "diag_copy_btn": "Скопировать в буфер обмена",
        "diag_copied_toast": "Диагностика скопирована в буфер обмена",
        "profiles_label": "Профиль:",
        "profiles_none": "Без профиля",
        "profiles_save_btn": "Сохранить как...",
        "profiles_delete_btn": "Удалить",
        "profiles_name_prompt_title": "Новый профиль",
        "profiles_name_prompt_label": "Название профиля:",
        "profiles_saved_toast": "Профиль сохранён: ",
        "profiles_deleted_toast": "Профиль удалён: ",
        "profiles_applied_toast": "Профиль применён: ",
        "profiles_delete_confirm": "Удалить профиль \"%s\"?",
        "apps_view_routes": "Маршруты",
        "apps_view_exceptions": "Исключения",
        "apps_view_monitor": "Активные соединения",
        "exceptions_info": "Отметьте приложения, которые НИКОГДА не должны идти через прокси (банк-клиенты, антивирус, RDP). Такие приложения будут заблокированы для выбора во вкладке \"Маршруты\".",
        "exceptions_locked_tooltip": "В исключениях - сначала уберите из списка исключений",
        "ctx_launch_one": "Запустить через прокси",
        "ctx_hide": "Скрыть из списка",
        "ctx_add_exception": "Добавить в исключения",
        "ctx_remove_exception": "Убрать из исключений",
        "speed_test_btn": "Тест скорости",
        "speed_test_running": "Измеряю скорость...",
        "speed_test_result": "Скорость загрузки: %.1f Мбит/с",
        "speed_test_fail": "Не удалось измерить скорость: ",
        "family_filter_title": "Семейная DNS-фильтрация",
        "family_filter_info": "Использует DNS-фильтры Cloudflare (1.1.1.1 for Families) - работает независимо от режима warp/proxy и от того, подключены ли вы сейчас.",
        "family_filter_off": "Выключено",
        "family_filter_malware": "Блокировать вредоносное ПО и фишинг",
        "family_filter_full": "Блокировать вредоносное ПО и контент 18+",
        "family_filter_apply": "Применить",
        "family_filter_applied": "Фильтрация DNS обновлена: ",
        "family_filter_fail": "Не удалось применить фильтрацию: ",
        "split_tunnel_info": "В режиме warp нельзя исключить отдельное приложение (это полный VPN) - зато можно вывести из туннеля конкретные домены или IP через встроенный split-tunnel Cloudflare. Трафик к ним пойдёт в обход WARP напрямую.",
        "split_tunnel_type_domain": "Домен",
        "split_tunnel_type_ip": "IP / подсеть (CIDR)",
        "split_tunnel_placeholder": "например: example.com или 192.168.1.0/24",
        "split_tunnel_empty": "Список пуст - добавьте домен или IP выше.",
        "split_tunnel_added": "Добавлено в split-tunnel: ",
        "split_tunnel_removed": "Убрано из split-tunnel: ",
        "split_tunnel_apply_fail": "warp-cli отклонил команду (обновите WARP или проверьте формат значения)",
        "warp_plus_title": "Активация WARP+",
        "warp_plus_info": "Введите лицензионный ключ WARP+ (Team key или Warp+ license), если он у вас есть. Обычный WARP работает и без ключа.",
        "warp_plus_placeholder": "XXXXXXXX-XXXXXXXX-XXXXXXXX",
        "warp_plus_activate": "Активировать",
        "warp_plus_success": "Лицензия WARP+ активирована",
        "warp_plus_fail": "Не удалось активировать лицензию: ",
    },
    "en": {
        "connect": "Connect",
        "disconnect": "Disconnect",
        "connected": "Connected",
        "disconnected": "Disconnected",
        "connecting": "Connecting...",
        "disconnecting": "Disconnecting...",
        "toast_connected": "WARP connected",
        "toast_disconnected": "WARP disconnected",
        "toast_error": "An error occurred",
        "toast_saved": "Settings saved",
        "speed": "Speed",
        "download": "Download",
        "upload": "Upload",
        "endpoint": "Endpoint",
        "language": "Language",
        "dns": "DNS server",
        "auto_dns": "Auto-select DNS",
        "settings": "Settings",
        "help": "Help",
        "stalzone": "STALZONE",
        "apps": "Routes",
        "system": "System",
        "monitor": "Monitor",
        "quick": "Quick",
        "control": "Control",
        "log": "Log",
        "warp_region": "WARP region",
        "dns_description": "DNS server translates domain names to IP addresses. Faster DNS speeds up website loading.",
        "quick_intro": "One click - WARP connected. Status, IP and a live speed graph are shown below.",
        "quick_hint": "Mode and parameters are in the Control tab.",
        "mode_label": "Mode",
        "mode_warp": "warp (full VPN, including voice)",
        "mode_proxy": "proxy (selective, SOCKS5, TCP only)",
        "port_label": "SOCKS5 proxy port",
        "endpoint_hint": "Custom WARP endpoint (advanced, optional)",
        "endpoint_placeholder": "or enter custom IP:port",
        "endpoint_note": "Works only in warp mode. Official client accepts IP:port.",
        "connect_warp": "Connect WARP",
        "disconnect_warp": "Disconnect",
        "diagnostics": "Diagnostics",
        "check_ip": "Check IP and country",
        "log_title": "Log",
        "apps_title": "Selective proxying",
        "apps_info": "Check apps that should go through the proxy. Works only in proxy mode (SOCKS5).",
        "search_placeholder": "Search by name...",
        "all_categories": "All categories",
        "cat_games": "Games",
        "cat_browsers": "Browsers",
        "cat_messengers": "Messengers",
        "cat_office": "Office & documents",
        "cat_dev": "Development",
        "cat_media": "Media",
        "cat_other": "Other",
        "refresh_list": "Refresh list",
        "launch_checked": "Launch checked via proxy",
        "hide_selected": "Hide from list",
        "add_manual": "Add app manually",
        "exe_placeholder": "Path to .exe...",
        "browse": "Browse",
        "add": "Add",
        "sys_title": "System proxy (proxy mode only)",
        "sys_check": "Enable system proxy (all traffic through SOCKS5)",
        "sys_info": "Routes system traffic through WARP's SOCKS5 proxy. Some apps (e.g. Firefox) do not read the Windows system proxy - configure the proxy inside those apps directly (socks5, host 127.0.0.1, port as set above).",
        "utilities": "Utilities",
        "flush_dns": "Flush DNS cache",
        "clear_proxy": "Clear proxy registry settings",
        "stalzone_title": "Force region for STALZONE",
        "stalzone_info": "sc_forced_realm file is placed in the game root folder to force region.\nThe program will auto-detect the installed game and offer region selection.\nIf path not found, set it manually.",
        "game_path": "Game path:",
        "stalzone_placeholder": "e.g. D:\\Steam\\steamapps\\common\\STALZONE",
        "auto_find": "Auto-find game",
        "select_region": "Select region:",
        "check_ping": "Check ping to regions",
        "apply_region": "Apply region file",
        "stalzone_status": "Status: not applied",
        "settings_connection": "Connection",
        "auto_reconnect": "Auto-reconnect on connection loss",
        "dns_label": "DNS server:",
        "auto_dns_btn": "Auto-select",
        "autostart": "Autostart",
        "autostart_check": "Launch XaraProxy with Windows",
        "autostart_action": "On program startup:",
        "autostart_nothing": "Do nothing - just open window",
        "autostart_connect": "Connect WARP immediately",
        "autostart_connect_apps": "Connect WARP and launch checked apps",
        "interface": "Interface",
        "ui_level": "UI level:",
        "lang_label": "Language:",
        "ui_hint_simple": "\"simple\" shows Quick, Control, Settings and Help.",
        "ui_hint_advanced": "\"advanced\" opens Routes, System, Monitor and a custom WARP endpoint.\nThe STALZONE tab is always visible.",
        "reset": "Reset",
        "reset_btn": "Reset all configuration",
        "reset_info": "Deletes saved settings and restarts the program.",
        "save_settings": "Save settings",
        "help_install_title": "WARP Installation",
        "help_status_installed": "Status: WARP is installed and ready.",
        "help_status_not_installed": "Status: WARP not found. Click the button below to install.",
        "help_install_btn": "Download and install WARP",
        "help_install_btn_done": "Installation not required",
        "help_instructions": "Instructions",
        "help_text_proxy": "Proxy mode (selective): WARP opens a local SOCKS5 proxy on 127.0.0.1. Only checked apps go through it (TCP). Voice (UDP) does not work through SOCKS5 - use warp mode if you need voice.",
        "help_text_warp": "Warp mode (full VPN): all traffic goes through the tunnel, including voice, but all apps change visible region simultaneously.",
        "help_text_choose": "Not sure what to choose: start with the Quick tab - warp mode, no custom endpoint.",
        "help_text_diagnostics": "Diagnostics: the \"Check IP and country\" button in Control tab shows what external sites see, using real SOCKS5 DNS tunneling.",
        "help_text_autostart": "Autostart: in Settings you can launch with Windows and automatically connect WARP (and launch checked apps).",
        "help_text_stalzone": "STALZONE: forces the game region by creating sc_forced_realm in the game root.",
        "help_text_browsers": "Browsers: Chrome and Edge are launched with --proxy-server=socks5://127.0.0.1:port and genuinely route through the proxy. Firefox does not accept a proxy from the command line - configure SOCKS5 manually in about:preferences or use FoxyProxy.",
        "tray_connect": "Connect WARP",
        "tray_disconnect": "Disconnect WARP",
        "tray_show": "Show window",
        "tray_quit": "Quit",
        "minimized_to_tray": "Minimized to tray. WARP continues working.",
        "admin_required": "Admin rights needed",
        "admin_restart": "WARP installation requires admin rights. Restart as administrator?",
        "sys_proxy_admin": "System proxy needs admin rights.",
        "autostart_fail": "Could not set autostart in registry.",
        "warp_not_installed": "WARP not installed. Open the Help tab.",
        "dns_checking": "Checking DNS servers...",
        "dns_fastest": "Fastest DNS: ",
        "app_added": "Added: ",
        "app_exists": "App already in list",
        "select_app": "Select an app to hide.",
        "hide_confirm": "Hide",
        "hide_message": "Hide \"%s\" from list?",
        "no_apps_checked": "Check at least one app",
        "proxy_mode_only": "This works only in proxy mode.",
        "warp_not_connected": "WARP not connected",
        "start_now": "Start now?",
        "connect_first": "Connect WARP first.",
        "checking": "Checking...",
        "ip_country": "IP: %s . Country: %s . WARP: %s",
        "could_not_check": "Could not check: ",
        "pysocks_missing": "PySocks is not installed - Python cannot use SOCKS5 without it. Run: pip install \"requests[socks]\"",
        "mode_changed": "Mode changed, reconnecting...",
        "system_proxy_only": "System proxy works only in proxy mode.",
        "sys_proxy_enabled": "System SOCKS5 proxy enabled (127.0.0.1:%d)",
        "sys_proxy_failed": "Could not enable system proxy: ",
        "sys_proxy_disabled": "System proxy disabled and cleared",
        "dns_flushed": "DNS cache flushed",
        "dns_flush_fail": "Failed to flush DNS: ",
        "proxy_cleared": "Proxy settings cleared",
        "proxy_clear_fail": "Failed to clear settings: ",
        "settings_saved": "Settings saved",
        "reset_confirm": "Delete all settings?",
        "reset_done": "Configuration reset",
        "reset_fail": "Could not reset config: ",
        "download_installer": "Downloading...",
        "download_progress": "Downloading: %d%% (%.1f / %.1f MB)",
        "installer_sig_fail": "Invalid installer signature! Installation aborted.",
        "installer_success": "WARP installed successfully.",
        "installer_error": "Failed to install WARP: ",
        "warp_register": "Starting WARP registration...",
        "warp_connected": "WARP connected, IP: %s, region: %s",
        "warp_disconnected": "WARP disconnected",
        "warp_connecting": "Connecting...",
        "warp_failed": "Connection failed",
        "scanning": "Scanning",
        "apps_found": "Apps found: ",
        "launched_via_proxy": "Launched via proxy: ",
        "launch_error": "Launch error",
        "launched_count": "Launched apps: ",
        "launch_firefox_warning": "Firefox does not support a command-line proxy - configure SOCKS5 manually.",
        "stalzone_file_created": "sc_forced_realm created in %s with region %s",
        "stalzone_file_fail": "Failed to create file: ",
        "stalzone_game_found": "Game folder found: ",
        "stalzone_game_not_found": "Could not find game folder. Set the path manually.",
        "stalzone_path_set": "Path not set or does not exist.",
        "stalzone_file_exists": "File exists, content: ",
        "stalzone_file_empty": "(empty)",
        "stalzone_file_read_error": "File exists but could not be read",
        "stalzone_file_missing": "File missing. Will be created on apply.",
        "stalzone_apply_success": "Region %s applied",
        "stalzone_ping_start": "Pinging regions...",
        "stalzone_ping_result": "%s: %d ms",
        "stalzone_ping_unavailable": "%s: unavailable",
        "stalzone_fastest": "Fastest region: %s (%d ms)",
        "stalzone_ping_fail": "Could not determine ping to any region.",
        "endpoint_set": "Endpoint set to: ",
        "endpoint_fail": "Custom endpoint failed, using default",
        "region_set": "Region set to: ",
        "region_fail": "Failed to set region, using default",
        "warp_inactive": "WARP not active in trace, traffic may not be tunneled",
        "connection_lost": "Connection lost (attempt %d)",
        "reconnecting": "Reconnecting in %d s...",
        "reconnected": "Reconnected. IP: %s, country: %s",
        "reconnect_failed": "Reconnection failed",
        "reconnect_stop": "Too many reconnect attempts, stopping",
        "registering": "Registering device...",
        "register_fail": "Failed to register device",
        "mode_set": "Mode set to",
        "no_endpoint": "Custom endpoint failed, using default",
        "monitor_title": "Active connections through proxy",
        "monitor_info": "Shows processes with open connections to the local SOCKS5 proxy port.",
        "monitor_col_pid": "PID",
        "monitor_col_name": "Process",
        "monitor_col_addr": "Remote address",
        "monitor_empty": "No active connections through the proxy.",
        "monitor_scan_fail": "Could not scan connections: ",
        "security": "Security",
        "security_title": "Security Center",
        "security_intro": "A quick overview of what is protecting your connection right now.",
        "sec_warp_status": "WARP tunnel",
        "sec_kill_switch": "Kill Switch",
        "sec_system_proxy": "System proxy",
        "sec_cli_signature": "warp-cli.exe signature",
        "sec_state_on": "Active",
        "sec_state_off": "Off",
        "sec_state_unknown": "Unknown",
        "sec_signature_ok": "Signature valid",
        "sec_signature_bad": "Signature NOT verified!",
        "sec_signature_missing": "WARP not found",
        "leak_test": "Check IP/DNS leak",
        "leak_test_running": "Testing for leaks...",
        "leak_test_ok": "No leak detected. Only the Cloudflare IP is visible.",
        "leak_test_warn": "Warning: traffic does not appear to be going through the WARP tunnel.",
        "leak_test_fail": "Could not run the test: ",
        "kill_switch_title": "Kill Switch",
        "kill_switch_label": "Block all internet traffic if WARP disconnects (Kill Switch)",
        "kill_switch_info": "Adds a temporary Windows Firewall rule that blocks all outbound traffic if WARP\ndisconnects unexpectedly. The rule is removed when you disconnect manually\nor turn Kill Switch off. Requires administrator rights.",
        "kill_switch_admin_q": "Kill Switch requires administrator rights to manage the firewall. Restart as administrator?",
        "kill_switch_blocked_toast": "Kill Switch: internet blocked until WARP reconnects",
        "unsaved_title": "Unsaved changes",
        "unsaved_body": "You have unsaved settings changes. Save them before exiting?",
        "autostart_default_note": "By default the app does NOT auto-connect WARP - only when you press Connect yourself.",
        "wizard_welcome_title": "Welcome to XaraProxy",
        "wizard_welcome_body": "XaraProxy is a convenient manager for Cloudflare WARP.\n\nWith it you can:\n- Protect your connection via WARP\n- Route selected apps through a local SOCKS5 proxy\n- Force the game region for STALZONE\n- Use a Kill Switch to stop leaks if WARP drops\n\nWe will guide you through a quick setup. XaraProxy will NOT connect\nautomatically - you decide when to connect, every time.",
        "wizard_lang_title": "Choose a language",
        "wizard_lang_body": "Pick your interface language. You can always change it later in Settings.",
        "wizard_lang_label": "Interface language:",
        "wizard_install_title": "WARP installation",
        "wizard_install_body": "WARP was not found on your computer.\nClick the button below to download the installer to the program folder.\nAfter the download, the program will verify its digital signature.\nIf the signature is valid, the installer will open.\n\nIMPORTANT: after installation, close the WARP window that opens automatically.\nThis is required for this program to control it correctly.",
        "wizard_download_btn": "Download and run the WARP installer",
        "wizard_downloading": "Downloading...",
        "wizard_final_title": "Registration and mode selection",
        "wizard_final_body": "Please wait while we check the WARP installation and register it.\nIf WARP is already installed or you just installed it, click Finish.",
        "wizard_mode_label": "Select preferred mode:",
        "wizard_connect_now": "Connect to WARP right after finishing setup",
        "wizard_connect_hint": "Left unchecked, XaraProxy opens ready but disconnected - you press Connect\nwhenever you want. This is the recommended, safer default.",
        "watchdog_service_down": "The Cloudflare WARP service isn't responding - attempting recovery...",
        "watchdog_service_recovered": "The Cloudflare WARP service is back up",
        "sound_enabled_label": "Sound notifications",
        "sound_enabled_info": "Short, gentle sounds on connect, disconnect and warnings. Fully synthesized by the app - no third-party files.",
        "diag_export_title": "Support diagnostics",
        "diag_export_info": "Bundles version, WARP status, Kill Switch/proxy state and the latest log lines into one file - no personal data such as paths to your programs. Attach this file to a support request.",
        "diag_export_btn": "Export diagnostics",
        "diag_export_saved": "Diagnostics file saved: ",
        "diag_export_fail": "Could not save the file: ",
        "diag_copy_btn": "Copy to clipboard",
        "diag_copied_toast": "Diagnostics copied to clipboard",
        "profiles_label": "Profile:",
        "profiles_none": "No profile",
        "profiles_save_btn": "Save as...",
        "profiles_delete_btn": "Delete",
        "profiles_name_prompt_title": "New profile",
        "profiles_name_prompt_label": "Profile name:",
        "profiles_saved_toast": "Profile saved: ",
        "profiles_deleted_toast": "Profile deleted: ",
        "profiles_applied_toast": "Profile applied: ",
        "profiles_delete_confirm": "Delete profile \"%s\"?",
        "apps_view_routes": "Routes",
        "apps_view_exceptions": "Exceptions",
        "apps_view_monitor": "Active connections",
        "exceptions_info": "Check apps that should NEVER go through the proxy (banking apps, antivirus, RDP). These apps will be locked out of selection in the Routes view.",
        "exceptions_locked_tooltip": "In exceptions - remove it from the exceptions list first",
        "ctx_launch_one": "Launch via proxy",
        "ctx_hide": "Hide from list",
        "ctx_add_exception": "Add to exceptions",
        "ctx_remove_exception": "Remove from exceptions",
        "speed_test_btn": "Speed test",
        "speed_test_running": "Measuring speed...",
        "speed_test_result": "Download speed: %.1f Mbps",
        "speed_test_fail": "Could not measure speed: ",
        "family_filter_title": "Family DNS filtering",
        "family_filter_info": "Uses Cloudflare's own DNS filters (1.1.1.1 for Families) - works independently of warp/proxy mode and of whether you're currently connected.",
        "family_filter_off": "Off",
        "family_filter_malware": "Block malware and phishing",
        "family_filter_full": "Block malware and adult content",
        "family_filter_apply": "Apply",
        "family_filter_applied": "DNS filtering updated: ",
        "family_filter_fail": "Could not apply filtering: ",
        "split_tunnel_info": "In warp mode you can't exclude a single application (it's a full VPN) - but you CAN take specific domains or IPs out of the tunnel using Cloudflare's own split-tunnel feature. Traffic to them goes around WARP directly.",
        "split_tunnel_type_domain": "Domain",
        "split_tunnel_type_ip": "IP / subnet (CIDR)",
        "split_tunnel_placeholder": "e.g. example.com or 192.168.1.0/24",
        "split_tunnel_empty": "List is empty - add a domain or IP above.",
        "split_tunnel_added": "Added to split-tunnel: ",
        "split_tunnel_removed": "Removed from split-tunnel: ",
        "split_tunnel_apply_fail": "warp-cli rejected the command (update WARP or check the value's format)",
        "warp_plus_title": "WARP+ activation",
        "warp_plus_info": "Enter a WARP+ license key (Team key or Warp+ license) if you have one. Regular WARP works fine without a key.",
        "warp_plus_placeholder": "XXXXXXXX-XXXXXXXX-XXXXXXXX",
        "warp_plus_activate": "Activate",
        "warp_plus_success": "WARP+ license activated",
        "warp_plus_fail": "Could not activate the license: ",
    }
}

_current_lang = "ru"

def _t(key: str) -> str:
    return STRINGS.get(_current_lang, STRINGS["ru"]).get(key, key)

def set_language(lang_code: str) -> None:
    global _current_lang
    if lang_code in STRINGS:
        _current_lang = lang_code